attach "db.sqlite3" as db1;
delete from db1.courses_score where id=7;
delete from db1.courses_score where id=8;
delete from db1.courses_score where id=9;
delete from db1.courses_score where id=10;
delete from db1.courses_score where id=11;
delete from db1.courses_score where id=12;
delete from db1.courses_score where id=13;
delete from db1.courses_score where id=14;
delete from db1.courses_score where id=15;
delete from db1.courses_score where id=16;
delete from db1.courses_score where id=17;
delete from db1.courses_score where id=18;
update db1.courses_score set id=7 where id=19;
update db1.courses_score set id=8 where id=20;
update db1.courses_score set id=9 where id=21;
update db1.courses_score set id=10 where id=22;
update db1.courses_score set id=11 where id=23;
update db1.courses_score set id=12 where id=24;
update db1.courses_score set id=13 where id=25;
update db1.courses_score set id=14 where id=26;
update db1.courses_score set id=15 where id=27;
update db1.courses_score set id=16 where id=28;
update db1.courses_score set id=17 where id=29;
update db1.courses_score set id=18 where id=30;
update db1.courses_score set id=19 where id=31;
update db1.courses_score set id=20 where id=32;
update db1.courses_score set id=21 where id=33;
update db1.courses_score set id=22 where id=34;
update db1.courses_score set id=23 where id=35;
update db1.courses_score set id=24 where id=36;
update db1.courses_score set id=25 where id=37;
update db1.courses_score set id=26 where id=38;
update db1.courses_score set id=27 where id=39;
update db1.courses_score set id=28 where id=40;
update db1.courses_score set id=29 where id=41;
update db1.courses_score set id=30 where id=42;
