attach "db.sqlite3" as db1;
-- update db1.courses_course set id=1, name="Project1", course_number="CN404", year=2016, semester=1, description="Project1", major="Computer" where id=1;
-- update db1.courses_gradecriteria set id=11 where id=13;
-- update db1.courses_gradecriteria set id=12 where id=14;
-- update db1.courses_gradecriteria set id=13 where id=15;
-- update db1.courses_gradecriteria set id=14 where id=16;
-- update db1.courses_gradecriteria set id=15 where id=17;
-- update db1.courses_gradecriteria set id=16 where id=18;
-- update db1.courses_gradecriteria set id=17 where id=19;
-- update db1.courses_gradecriteria set id=18 where id=20;
-- update db1.courses_gradecriteria set id=19 where id=21;
-- update db1.courses_gradecriteria set id=20 where id=22;
-- update db1.courses_gradecriteria set id=21 where id=23;
-- update db1.courses_gradecriteria set id=22 where id=24;
-- update db1.courses_gradecriteria set id=23 where id=25;
-- update db1.courses_gradecriteria set id=24 where id=26;
-- update db1.courses_score set point=-100 where point=0;
update db1.accounts_student set student_picture = '/home/littledao/Downloads/img/me.jpg' where student_id=5610613365;
update db1.accounts_student set student_picture = '/home/littledao/Downloads/img/taeyeon.png' where student_id=5610611111;
update db1.accounts_student set student_picture = '/home/littledao/Downloads/img/tiffany.jpg' where student_id=5610612222;
update db1.accounts_student set student_picture = '/home/littledao/Downloads/img/jessica.jpg' where student_id=5610613333;
update db1.accounts_student set student_picture = '/home/littledao/Downloads/img/yuri.jpg' where student_id=5610614444;
update db1.accounts_student set student_picture = '/home/littledao/Downloads/img/sunny2.jpg' where student_id=5610615555;
update db1.accounts_student set student_picture = '/home/littledao/Downloads/img/hyohyeon2.jpg' where student_id=5610616666;
update db1.accounts_student set student_picture = '/home/littledao/Downloads/img/seohyeon.jpeg' where student_id=5610617777;
update db1.accounts_student set student_picture = '/home/littledao/Downloads/img/yoona2.jpg' where student_id=5610618888;
update db1.accounts_student set student_picture = '/home/littledao/Downloads/img/sooyoung.jpg' where student_id=5710619999;
update db1.accounts_student set student_picture = '/home/littledao/Downloads/img/duan.jpg' where student_id=5710611234;
