attach "db.sqlite3" as db1;
update db1.courses_gradecriteria set id=10 where id=12;
update db1.courses_gradecriteria set id=11 where id=13;
update db1.courses_gradecriteria set id=12 where id=14;
update db1.courses_gradecriteria set id=13 where id=15;
update db1.courses_gradecriteria set id=14 where id=16;
update db1.courses_gradecriteria set id=15 where id=17;
update db1.courses_gradecriteria set id=16 where id=18;
update db1.courses_gradecriteria set id=17 where id=19;
update db1.courses_gradecriteria set id=18 where id=20;
update db1.courses_gradecriteria set id=19 where id=21;
update db1.courses_gradecriteria set id=20 where id=22;
update db1.courses_gradecriteria set id=21 where id=23;
update db1.courses_gradecriteria set id=22 where id=24;
update db1.courses_gradecriteria set id=23 where id=25;
update db1.courses_gradecriteria set id=24 where id=26;
